name: ci

on: [push]

jobs:
  container:
    runs-on: ubuntu-latest
    container:
      image: boeegh/dotnet-nvm:latest
      volumes:
      - ${{ github.workspace }}:/app
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3      
      - name: Build with npm and dotnet
        run: |
          nvm use 18
          npm install
          npm run build
          dotnet publish -c Release -o /publish
      - name: Archive production artifacts
        uses: actions/upload-artifact@v3
        with:
          name: app
          path: |
            /publish
            !/publish/**/package.json
            !/publish/**/package-lock.json
